### ISSUE TITLE
希望加入 cache 功能

### ISSUE THREAD

**Issue by yize** [Jias/natty-fetch#13]
1. 增加 `middleware` 机制。
2. 新增 `cachePlugin` （支持 `sessionStorage` 、 `localStorage` 、`内存` 等缓存方式「服务端甚至可以直接用 `tair`」）。
3. `cache` 可以采用 `sha1` 来做 `key` 。
4. `key` 的唯一性需要考虑。

**Comment by Jias** [comment]
doing...

**Comment by Jias** [comment]
从`v2.0.0`版本开始缓存功能。

* 支持三种方式的缓存：`localStorage`(默认), `sessionStorage`, `variable`。
* 支持三种有效性验证：标记(`id`)、有效期长(`duration`)、有效期至(`until`)。
* 隐身模式下，有些浏览器不支持`localStorage`，此时自动降级为`variable`模式。

示例：

```js
const nattyFetch = require('natty-fetch');
const context = nattyFetch.context();
context.create({
    getCitys: {
        url: '//example.com/api/getCitys',
        storage: {
            type: 'localStorage', // 默认
            id: 'v1.0'
        }
    }
});
```

`storage`的详细配置说明见[natty-storage文档](https://github.com/Jias/natty-storage)
