### ISSUE TITLE
mock添加jsonp的支持

### ISSUE THREAD

**Issue by paseo** [Jias/natty-fetch#14]
场景是，正式环境请求本地的api。测试时请求第三方站点的mock api。

**Comment by Jias** [comment]
这个功能是有的, 见`mock`，`mockUrl`配置。

**Comment by paseo** [comment]
正式环境和mock环境分别应用不同的type的时候，没有做相应转换
比如，正式环境请求本地的是json，测试环境请求第三方站点要求是jsonp。酱紫。
