### ISSUE TITLE
目前的用法偏向项目级，是否能够提供更加核心向的 fetchAPI

### ISSUE THREAD

**Issue by eternalsky** [Jias/natty-fetch#15]
组件级对依赖的要求就是尽量轻，而通常组件中发起请求只会有一到两个，所以不需要复杂的环境配置。如果能够有更轻更简便的用法，相信可以得到更好的推广。

**Comment by Jias** [comment]
有道理，组件级使用再想想如何简化。

**Comment by Jias** [comment]
support form v2.0.0
