### ISSUE TITLE
偶尔出现的报错

### ISSUE THREAD

**Issue by FE-Girl** [Jias/natty-fetch#16]
chrome浏览器  

版本：50.0.2661.102（64-bit）

报错信息：
![](https://img.alicdn.com/tps/TB1QlWXKXXXXXaZXXXXXXXXXXXX-1930-49.png)

![](https://img.alicdn.com/tps/TB1kcJ5KXXXXXX1XpXXXXXXXXXX-822-294.png)

**Comment by Jias** [comment]
fixed in v1.0.3
