### ISSUE TITLE
context.create是不是返回执行后，同时返回结果更好。

### ISSUE THREAD

**Issue by xuguogang** [jias/natty-fetch#17]
从语义还有使用上来说context.create执行后返回结果(return ctx.api;)更合适，

let context = nattyFetch.context();

let apis= context.create(......);

export default apis;

**Comment by Jias** [comment]
`context.create`没有直接返回`apis`，是因为要支持可以根据条件或语义来多次调用的。

```
let context = nattyFetch.context();

// 调用
context.create({
    'user.getName': {},
    'user.getPhone': {}
});

// 再通用
context.create({
    'getList': {},
    'getOrder': {}
});

...
```

**Comment by xuguogang** [comment]
那我觉的可以context.create()时放到局部变量中，并返回创建的这部分，context.api时可以返回全部。

**Comment by jias** [comment]
v3.0开始支持
