### ISSUE TITLE
FromBody要如何POST数据？

### ISSUE THREAD

**Issue by sparkleDai** [jias/natty-fetch#22]
netty对ajax方法进行了封装，无法通过ajax头来直接传递一个类的JSON数据，要怎么处理？
使用ajax，我们是这么处理的

```
$.ajax({
                    type: 'POST',
                    url: "/Api/XX",
                    contentType: 'application/json; charset=utf-8',//将json数据以request payload的形式发起请求
                    data: JSON.stringify(data),
                    success: function (response) {


                    }
                    catch (ex) {
                    }
                }
            });
```

使用natty的方式，已经设置了header，

```
 header: {
            'Accept': '_/_',
            'Content-Type': 'application/json; charset=utf-8',//将json数据以request payload的形式发起请求  
        }
```

但是针将JSON.stringfy(data)后的数据变成一长串，查代码发现是 var vars = t.makeVars(data)会修改它。
被转换后的数据如下:
0=%5B&1=%22&2=c&3=h&4=a&5=t&6=5&7=4&8=4&9=7&10=3&11=8&12=0&13=2&14=d&15=f&16=1&17=6&18=8&19=1&20=d&21=2&22=6&23=d&24=3&25=5&26=2&27=0&28=6&29=3&30=f&31=d&32=a&33=6&34=a&35=4&36=e&37=3&38=%22&39=%2C&40=%22&41=A&42=%22&43=%2C&44=%22&45=B&46=%22&47=%2C&48=%22&49=C&50=%22&51=%5D
这个数据明显是不对的。
natty要怎么设置才能实现，传输到后端可以被FromBody接收？

**Comment by sparkleDai** [comment]
已经设置了
 header: {
            'Accept': '*/*',
            'Content-Type': 'application/json; charset=utf-8',//将json数据以request payload的形式发起请求        
        }
但是针将JSON.stringfy(data)后的数据变成一长串，查代码发现是 var vars = t.makeVars(data)会修改它。
被转换后的数据如下:
0=%5B&1=%22&2=c&3=h&4=a&5=t&6=5&7=4&8=4&9=7&10=3&11=8&12=0&13=2&14=d&15=f&16=1&17=6&18=8&19=1&20=d&21=2&22=6&23=d&24=3&25=5&26=2&27=0&28=6&29=3&30=f&31=d&32=a&33=6&34=a&35=4&36=e&37=3&38=%22&39=%2C&40=%22&41=A&42=%22&43=%2C&44=%22&45=B&46=%22&47=%2C&48=%22&49=C&50=%22&51=%5D

**Comment by jias** [comment]
意思是发送前的数据就已经自己做过`JSON.stringfy`化了，然后真正发出去的数据又被natty内部执行了`param`化了，是这个意思吗？@sparkleDai

**Comment by sparkleDai** [comment]
是的，就是这个意思，目前采用的暂时处理方法是直接在源码中增加一个isOriginalData的配置，如果是的时候，不再参数化，直接ajax就可以了。
这个问题应该与《请考虑对options的处理切入点》的问题相似。

**Comment by jias** [comment]
@sparkleDai 好的，感谢反馈，这种情况会加入支持。

**Comment by LiangZugeng** [comment]
很不幸，我也遇到了同样的问题，post的json数据，即使是JSON.stringify后的raw的json字符串，也会被param()处理，变成服务端不可接受的数据。处理的语句是ajax.js文件中的ajax方法，下面这句：

`xhr.send(options.method === GET ? NULL : options.data !== NULL ? param(options.data, options.traditional) : NULL);`

目前看来只能：
1. fork一份Natty-Fetch修改源码，加个配置项然后决定是否调用param()
2. 改服务端的代码，接受form data格式的post

@sparkleDai ，你是怎么处理的？
@jias ，3.0的Schedule有了吗？

**Comment by jias** [comment]
原来如此，@LiangZugeng 如果你的fork改好了，提个PR过来吧，我合一下。
另外。v3.0，为了满足各种切入点处理的需求，加入了中间件的支持，使用方式改动非常大，我都是抽时间再写，发布时间还不能够保证。

**Comment by sparkleDai** [comment]
@LiangZugeng  加入isOriginalData配置项，一路往内部传递，然后内部判断。

**Comment by jias** [comment]
这个问题已解决了，最新版v2.4.2，在`POST`请求的配置中配置一下`header`即可，如下：

```js
context.create({
    add: {
        method: 'POST',
        header: {
            // 指定以POST请求的编码方式为JSON
            'Content-Type': 'application/json;charset=utf-8'
        }
    }
})

```

**Comment by LiangZugeng** [comment]
@sparkleDai @jias 问题已经解决。可以关掉了。
