### ISSUE TITLE
succes为false时建议返回整个response而不是response.error

### ISSUE THREAD

**Issue by jzlingmo** [jias/natty-fetch#28]
success为false的情况下对promise进行catch，大部分情况下服务端返回response.error都是空的，应该直接返回response方便判断其中的errorCode（或者其它字段）

代码地址 https://github.com/jias/natty-fetch/blob/master/src/natty-fetch.js#L455

**Comment by jias** [comment]
只要`fit`用得好，服务端怎么返回错误，`error`或其他任何表示错误的字段，放在哪里都不是问题。
