### ISSUE TITLE
希望开放跨域自定义 header

### ISSUE THREAD

**Issue by pfdgithub** [jias/natty-fetch#30]
应该由使用者决定是否启用跨域自定义头，而不是强制屏蔽。

**Comment by jias** [comment]
如果在跨域时发送了自定义`header`, 则:

标准浏览器(`Chrome, Firefox`等)有更严格的安全限制，所以会报错

```
Request header field xxx is not allowed by Access-Control-Allow-Headers in preflight response.
```

 `IE`浏览器不报错

natty-fetch中，为避免使用者"犯错(标准浏览器都不能运行，无意义)"，也为了统一浏览器行为，所以屏蔽了跨域时的自定义`header`。

**Comment by pfdgithub** [comment]
标准浏览器对于跨域自定义header，需要进行预请求检查，可在服务端配置开启。
[HTTP访问控制(CORS)](https://developer.mozilla.org/zh-CN/docs/Web/HTTP/Access_control_CORS#预请求)

**Comment by jias** [comment]
好的，下个版本放开自由，让用户自己解决安全配置。

**Comment by jias** [comment]
fixed in v2.2.0
