### ISSUE TITLE
收集一下是否有外部公司(or团队)在使用`natty-fetch`？

### ISSUE THREAD

**Issue by jias** [jias/natty-fetch#31]

**Comment by pfdgithub** [comment]
现在做的一个项目在用。因为之前用过natty-db，感觉挺精炼简单，就继续用了。
当然最重要的原因是，有相对详细的中文文档，理解起来快。

**Comment by pfdgithub** [comment]
现在做的一个项目在用。因为之前用过natty-db，感觉挺精炼简单，就继续用了。
当然最重要的原因是，有相对详细的中文文档，理解起来快。

**Comment by kcshan** [comment]
外包算外部团队不  natty-db很好用 小而美 不知道natty-fetch怎么样

**Comment by a4870326** [comment]
有在用。。

**Comment by kcshan** [comment]
哥 我在给你推 简历上都写了 发自网易邮箱大师 在2017年06月27日 14:02，jia song 写道： Closed #31. — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or mute the thread.
