### ISSUE TITLE
safari 隐身/无痕模式下 web storage 被禁用，出现异常 QuotaExceededError

### ISSUE THREAD

**Issue by pfdgithub** [jias/natty-fetch#32]
检测 web storage 是否支持的代码，没有 try catch 异常。造成 natty-fetch 执行异常。
https://github.com/jias/natty-storage/blob/master/src/natty-storage.js#L36

**Comment by jias** [comment]
好的，发个小版本修复，感谢反馈。

**Comment by jias** [comment]
fixed in natty-storage@1.1.2

**Comment by pfdgithub** [comment]
建议把 natty-fetch 对 natty-storage 的依赖也升级为 [1.1.2](https://github.com/jias/natty-fetch/blob/master/package.json#L74)   
由于 npm3 的[依赖解析方案](https://docs.npmjs.com/how-npm-works/npm3)，是按照 package.json 中的依赖顺序处理多版本共存的。  
默认情况下， natty-fetch 排在 natty-storage 前面，于是先安装 1.1.1 版本，再安装 1.1.2 版本。造成 natty-fetch 使用的其实还是 1.1.1 版本，除非手动把 natty-storage 放在前面。

**Comment by jias** [comment]
ok
