### ISSUE TITLE
怎么在fit中获取response 的http code

### ISSUE THREAD

**Issue by GeorgeXu** [jias/natty-fetch#33]
我们是通过返回的http code来判断 请求是成功还是失败的，所以要拿http code 决定success 还是error，但是看了下，回调函数中好像没有方法获取http code

**Comment by jias** [comment]
你说的http code是指xhr的status字段吗？

**Comment by beita1991** [comment]
是的，就是xhr对象在外面拿不到

**Comment by jias** [comment]
先给了临时方案让你可以继续，下个版本会在`fit`中暴露`xhr`对象，到时小改一下即可。

临时方案如下：

```
context.create({
    yourApi: {
        url: host + 'api/404',
        fit: function() {
            // 通过接口的私有属性获取`xhr`对象
            const xhr = context.api.yourApi._requester
        }
    }
});
```

**Comment by GeorgeXu** [comment]
好的，谢谢

**Comment by singleclown** [comment]
这个移动端钉钉前端开发，怎么用啊

**Comment by jias** [comment]
@singleclown 你的问题是`natty-fetch`怎么用？

**Comment by singleclown** [comment]
我对这两个框架都表示不懂，开发钉钉是不是不用这两个也行，然后对里面的事例和应用场景与使用都不明白，如果大神愿意指导小白，尔等虚心接受并感谢

**Comment by jias** [comment]
从`v2.5.3`开始，`fit`回调中可以去到`ajax`请求的状态码。

```js
fit(response, vars) {
  // 需要的状态码
  vars.requester.status
}
```
