### ISSUE TITLE
natty-fetch什么时候支持restful,钉钉开发中需求,急等中...

### ISSUE THREAD

**Issue by ghost** [jias/natty-fetch#34]
当前,nowa框架已经很好的支持了前端的开发, 前后端分离的. 都在用restful API规范的接口. 
natty-fetch,怎么能不支持呢? 
现在,经过钉钉的推荐,已经发行natty是非常好的工具了,但是resful的不支持,确实是一个很大的遗憾.
尤其是作为标榜一个数据api接口的优秀工具.

**Comment by gbk** [comment]
:+1:  +1

**Comment by LiangZugeng** [comment]
@xttianma @jias 

借贴问个相关问题。我刚开始做钉钉开发，看到官方推荐数据访问用Natty-Fetch就来了，我的后台是ASP.NET Core MVC Web API开发的Restful API，使用了PUT/DELETE/PATCH等命令，但Natty-Fetch只支持GET/POST两个命令，我的问题如下：
1. 在Natty-Fetch支持Restful API格式之前，我是不是需要把我的Restful API另外再封装一层，比如编辑的时候使用POST，content设计为这样{ action: 'Edit', data: { name: 'newName', age: 35 } }？在比如删除的时候用GET，然后带上?Action=Delete&ID=2？请问有没有比这个更好的后端接口设计方案？
2. 阿里钉钉开发团队在开发钉钉客户端的时候数据访问组件用的也是Natty-Fetch吗？如果不是的话他们用的是什么？

请帮忙解答这两个问题，谢谢。

**Comment by jias** [comment]
support from v2.4.0
