### ISSUE TITLE
timeout && 并发 的bug

### ISSUE THREAD

**Issue by peng2e** [jias/natty-fetch#38]
设置了timeout ，并发请求会cancled掉前面的一个请求~  大bug！！！ 速度解决……

**Comment by ISAISAI** [comment]
遇到同样问题

**Comment by ISAISAI** [comment]
setTimeout(function () {
           
            if (t.api.pending && t.api._requester) {
                // 取消请求
                t.api.abort();
                var error = {
                    timeout: TRUE$$1,
                    message: 'Timeout By ' + config.timeout + 'ms.'
                };

                defer.reject(error);
                event.fire('g.reject', [error, config]);
                event.fire(t.api.contextId + '.reject', [error, config]);
            }
        }, config.timeout);

**Comment by kcshan** [comment]
遇到同样问题

**Comment by jias** [comment]
fixed in v2.3.0

**Comment by jias** [comment]
fixed in v2.3.0
