### ISSUE TITLE
动态修改mock属性

### ISSUE THREAD

**Issue by walton007** [jias/natty-fetch#40]
我有一种使用场景是这样的：
一开始，使用的非mock数据， 
nattyFetch.setGlobal({
  mock: false
})
接下来用户想查看demo，我们必须使用mock数据了，测试尝试
nattyFetch.setGlobal({
  mock: true
})
然后不起作用，调用api请求数据仍然是实用的非mock数据

所以，是否能够存在一种机制能够，批量修改所有已经创建的context的mock属性

**Comment by jias** [comment]
你的需求是让`上层配置`覆盖`下层配置`，这个在设计层面肯定是不支持的，否则会出乱。

如果需要这个功能，可以在配置`context`的`mock`值时，加上自己的处理，比如：

```
const io = nattyFetch.context({
    mock: globalForceMock || contextMock
})
```
