### ISSUE TITLE
POST请求问题

### ISSUE THREAD

**Issue by jyxyt2016** [jias/natty-fetch#42]
POST时，框架内置Content-Type:application/x-www-form-urlencoded;
没办法重设，是否可以去掉此限制。

**Comment by jias** [comment]
`POST`时，如果没有配置`header`的`Content-Type`时，才会内部默`application/x-www-form-urlencoded`编码，如果想使用其他编码方式，可以自己制定Content-Type的值即可。

[v2.4.2的相关代码](https://github.com/jias/natty-fetch/blob/v2.4.2/src/ajax.js#L40)

举个例子，假设你像使用`json`编码，在[任何层级](https://github.com/jias/natty-fetch/blob/v2.4.2/docs/option_levels.md)的配置中，都可以加入如下`header`配置：

```
header: {
    'Content-Type': 'application/json;charset=utf-8'
}
```

**Comment by jyxyt2016** [comment]
@jias 用chrome跨域插件 程序中设置了header，设置无效。
用nginx设置header有效率
另一个问题：post方式能不能带qs

**Comment by jias** [comment]
`POST`配置`queryString`，我记录到需求里了。
`header`配置只影浏览器响发出请求时的信息，和chrome插件没关系，和服务端用什么更没关系。
这个问题可以关了。
