### ISSUE TITLE
Request Payload问题

### ISSUE THREAD

**Issue by jyxyt2016** [jias/natty-fetch#43]
JSON.stringify后：
{"user2Id":1000001,"salesTypeId":1000008,"cEquotsetId":1000000,"bpartner":"张三","phone":"13562591755","equipClassId":1000005,"equipModelId":1000013,"salesAmt":1000000,"downpaymentRate":0,"downpayment":0,"divideAmt":0,"divideNumber":0,"loanAmt":0,"loanNumber":0,"packDivideAmt":0,"packDivideNumber":0,"createdby":1000117}
POST提交，Request Payload如下：
![default](https://cloud.githubusercontent.com/assets/19221451/25368497/7d931054-29af-11e7-9510-79997c8466dd.png)
后台：@RequestBody没办法解析
![default](https://cloud.githubusercontent.com/assets/19221451/25370469/8d7d17cc-29bd-11e7-885e-445708c1635c.png)

**Comment by jias** [comment]
哪个版本？最新版已经修复了该问题。

**Comment by jyxyt2016** [comment]
natty-fetch 2.4.2
salt-fetch 2.0.3
这个版本还是那个问题。

**Comment by jias** [comment]
用`natty-fetch`，不要用`salt-fetch`了，另外，你可以贴下配置代码。

**Comment by jyxyt2016** [comment]
感谢答复!
去掉salt-fetch，直接用natty-fetch 2.4.2，还是没解决。
用postman没问题。
配置如下：
const nattyFetch = require('natty-fetch');
const context = nattyFetch.context({
    mockUrlPrefix: '/mock/',
    urlPrefix: 'http://192.168.0.1:8080/yhapi/jyx/',
    mock: false,
    //jsonp: true,
    withCredentials: false,
    traditional: true,
    urlStamp: true,
    // data: {
    //     _tb_token_: ''
    // },
    timeout: 5000,
    fit: function(response) {
        return {
            success: response.code==100,
            content: response.content,
            error: {
                errorMsg: response.message,
                errorCode: response.code,
                errorLevel: ''
            }
        }
    }
});

context.create('SomeModuleAPI', {
    getSomeInfo: {
        mockUrl: 'query/getSomeInfo.json',
        url: 'query/getSomeInfo.json'
    }
});

context.create('yhdd',{
    putEquot:{
        url:'equot/putEquot',
        data:{},
        method:'POST',
        //ignoreSelfConcurrent: true,
       // postDataFormat:'JSON',
        header: {
            'Content-Type': 'application/json;charset=utf-8'
        }
    }

});
module.exports = context.api;
以下请求有问题：
![default](https://cloud.githubusercontent.com/assets/19221451/25879421/38a74fda-3564-11e7-9d1c-a7feff73b1f2.png)
postman请求没问题
![default](https://cloud.githubusercontent.com/assets/19221451/25879481/81f9eda0-3564-11e7-97d2-31478c38eaa1.png)

**Comment by jyxyt2016** [comment]
@jias 以上反馈请帮助解答，谢谢！

**Comment by jias** [comment]
还是没有复现，使用下面代码测试，都是好的。

```js
const context = nattyFetch.context({
  urlPrefix: host
})

context.create({
  create: {
    url: `'api/order-create',`
    method: 'POST',
    header: {
      'Content-Type': 'application/json;charset=utf-8'
    },
    data: {
      // 静态数据
      foo: 'foo-value',
    },
  }
})

context.api.create({
  // 动态数据
  bar: 'bar-value',
}).then((content) => {
  // ...
})
```

发出去的`Request Payload`数据完全没问题。

**Comment by jyxyt2016** [comment]
@jias 去掉JSON.stringify()，payload正常了，如下：

另外：PUT时 可以设置 QueryString的功能增加了吗？
