### ISSUE TITLE
IE9报错：无法获取未定义或 null 引用的属性“Content-Type“

### ISSUE THREAD

**Issue by McLemore** [jias/natty-fetch#47]
引入的是：`import nattyFetch from "natty-fetch/dist/natty-fetch.pc.js"`

报错行数：604行

看了下代码，604行没有判断`header`为未定以或`null`的情况
而`header`是通过调用`setHeaders`方法获取的，`setHeaders`方法里首先会判断`xhr.setRequestHeader`是否存在，如果否，直接`return`，ie下 `!!xhr.setRequestHeader === true` 所以`header`将为`undefined`，然后就报错了。

报错截图
![image](https://cloud.githubusercontent.com/assets/8602185/26749765/4b18064e-4844-11e7-9c01-1f3e7ec4403d.png)

**Comment by jias** [comment]
描述的太详细了，感谢
