### ISSUE TITLE
POST 格式 multipart/form-data

### ISSUE THREAD

**Issue by balddonkey** [jias/natty-fetch#52]
由于需要上传图片视频的文件，所以需要用到content-type:multipart/form-data，但是没有找到如何设置，老板能指点一下吗。用'RAW'的方式手动在header里面配置会缺少boundary=----WebKitFormBoundaryAnxxxxxx这一段，然后也不能请求成功~好像是浏览器bug还是什么，Fetch库也存在这个问题，可以通过不设置content-type字段解决。

**Comment by jias** [comment]
现在上传文件功能，一般都使用专门的上传组件来做吧。因为上传功能不仅仅是“传”，还有大小，格式，个数这些验证功能，甚至有预览和上传进度功能。

所以不建议用`natty-fetch`做上传。

**Comment by jias** [comment]
最新版的natty-fetch支持设置header
