### ISSUE TITLE
重大 IE 兼容性问题: window.toString

### ISSUE THREAD

**Issue by MagicCube** [jias/natty-fetch#53]
···js
var isArray = function (v) {
    return toString.call(v) === ARRAY_TYPE
};
···

在这里你调用了 window.toString()，在 IE9 和 IE10 中是无法正常运行的，由于采用了 DEF 云端构建，受此代码影响的阿里巴巴、淘宝项目非常多，请尽快修复！

**Comment by jias** [comment]
fixed in [natty-storage@2.1.1](https://github.com/jias/natty-storage/blob/master/CHANGELOG.md)

**Comment by jias** [comment]
这个是`natty-storage`的错误，意外误删了一行代码，补上了。

```
const toString = Object.prototype.toString
```

**Comment by MagicCube** [comment]
多谢！
