### ISSUE TITLE
v2.5.2 为什么快速连续请求两次，必然有一次失败

### ISSUE THREAD

**Issue by balddonkey** [jias/natty-fetch#56]
快速请求两次，有一个请求根本不会到达后台，为什么呢~参数是不一样的啊，只能先换库了

**Comment by jias** [comment]
1. 用的是`natty-fetch`原版，还是`salt`版。
2. 可以贴一下代码帮你看看。

**Comment by balddonkey** [comment]
@jias  应该不是natty的问题，我用别的库也一样

**Comment by jias** [comment]
好的，感谢支持。
