### ISSUE TITLE
NattyFetch不支持async的配置吗？

### ISSUE THREAD

**Issue by fuxun2008** [jias/natty-fetch#67]
![image](https://user-images.githubusercontent.com/4995935/43683835-f3f2a390-98c6-11e8-9dd4-dd8bb6c6c6b7.png)

目前如果同时发出两个相同请求，后面一个会被cancel掉，大概率性的。
原因可能是async为true，两个异步请求并发导致的。
但是没有在文档里面看到async可以修改配置的

**Comment by jias** [comment]
你应该是在其他人的全局配置(`ignoreSelfConcurrent: true`)下使用的，默认是允许多个并发的。看一下文档中的`ignoreSelfConcurrent`配置。然后在你的接口配置中可以用`false`值覆盖一下，或者去问问全局配置为什么是`true`。
